import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/layout/navbar';
import { PageAnimation, PageTransitions } from '@/components/transitions';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageTransitions>
          <Navbar />
          <PageAnimation
            variants={{
              enter: { opacity: 1 },
              exit: { opacity: 0, transition: { duration: 2 } },
            }}
          >
            {children}
          </PageAnimation>
        </PageTransitions>
      </body>
    </html>
  );
}
